import { Metadata } from "next";
import "./global.css";
import Link from "next/link";

/* export const metadata : Metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};*/

export const metadata : Metadata = {
	title: {
		default: "Aprendiendo Next js",
		absolute: "",
		template: "%s - Aprendiendo Next.js"
	},
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="es">
			<body>
				<header>
					<h1>Cabecera de la App</h1>
					<ul>
						<li>
							<Link href="/">Inicio</Link>
						</li>
						<li>
							<Link href="/acerca">Acerca</Link>
						</li>
						<li>
							<Link href="/contacto">Contacto</Link>
						</li>
						<li>
							<Link href="/blog">Blog</Link>
							<ul>
								<li>
									<Link href="/blog/articulo-1">Articulo 1</Link>
								</li>
							</ul>
						</li>
						<li>
							<Link href="/productos">Productos</Link>
						</li>
						<li>
							<Link href="/login">Login</Link>
						</li>
						<li>
							<Link href="/registro">Registro</Link>
						</li>
						<li>
							<Link href="/password">Recuperar password</Link>
						</li>
						<li>
							<Link href="/dashboard">Dashboard</Link>
						</li>
					</ul>
				</header>
				<main>
					{children}
				</main>
				<footer>Pie de página</footer>
			</body>
		</html>
	);
}
